---
apiVersion: v1
kind: Service
metadata:
  name: overseerr-nodeport
  namespace: media-stack
spec:
  type: NodePort
  selector:
    app: overseerr
  ports:
  - port: 5055
    targetPort: 5055
    nodePort: 30055

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-nodeport
  namespace: media-stack
spec:
  type: NodePort
  selector:
    app: sonarr
  ports:
  - port: 8989
    targetPort: 8989
    nodePort: 30989

---
apiVersion: v1
kind: Service
metadata:
  name: radarr-nodeport
  namespace: media-stack
spec:
  type: NodePort
  selector:
    app: radarr
  ports:
  - port: 7878
    targetPort: 7878
    nodePort: 30878

---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-nodeport
  namespace: media-stack
spec:
  type: NodePort
  selector:
    app: indexer-stack
  ports:
  - port: 9696
    targetPort: 9696
    nodePort: 30696

---
apiVersion: v1
kind: Service
metadata:
  name: jackett-nodeport
  namespace: media-stack
spec:
  type: NodePort
  selector:
    app: indexer-stack
  ports:
  - port: 9117
    targetPort: 9117
    nodePort: 30670


---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-nodeport
  namespace: media-stack
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080

---
apiVersion: v1
kind: Service
metadata:
  name: plex-mcp-nodeport
  namespace: media-stack
spec:
  type: NodePort
  selector:
    app: plex
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30301
